package com.mycompany.calculator.basic_calculator;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;

import com.mycompany.calculator.basic_calculator.database.Database;
import com.mycompany.calculator.basic_calculator.database.EquationDAO;
import com.mycompany.calculator.basic_calculator.math.Equation;
import com.mycompany.calculator.basic_calculator.math.Tokenizer;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
    	/*
    	System.out.println( "Hello World!" );
        
        // A bug
        System.out.println(Arrays.toString(Tokenizer.tokenize("(5.4+ x ) *x -3.0")));
        System.out.println(Arrays.toString(Tokenizer.tokenize("(5.4+ x ) *x - 3.0")));
        
        // A bug: assertFalse(equation.isRoot(-5.8)); <false> but was <true>
        System.out.println(Arrays.toString(Tokenizer.tokenize("-1.3*5/x=1.2")));
        */
    	
    	// String sql = "CREATE TABLE equations (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, lhs text[] NOT NULL, rhs text[] NOT NULL, solution numeric(15, 5));";
    	
    	
    	// Equation equation = new Equation("x-3=2");
    	// System.out.println(EquationDAO.add(equation, 5));
    	
    }
}
